### ISSUE TITLE
Option for arbitrary alphabets

### ISSUE THREAD

**Issue by aphillippy** [marbl/Mash#14]
Reminder to expose an option for protein (or even arbitrary?) alphabets. This option should also shut off canonical mers and adjust the math based on alphabet size.

**Comment by ondovb** [comment]
I can think of these presets:
- nucleotide (default): ACGT, canonical, case-insensitive
- protein: 20 AA chars, case-insensitive
- roman: A-Z, case-insensitive (optionally?)
- ASCII: all 256 chars, no filtering

As far as allowing an arbitrary alphabet, I think it would make sense to accept a file of specific characters, rather than just a size. Otherwise there would be no way to ensure that two sketches with identical sizes could actually be meaningfully compared.

**Comment by ondovb** [comment]
Arbitrary alphabets (with a protein preset) are now in master. The full alphabet is always stored in the Capnp, and old files are retrofitted as nucleotide when loaded. There is also a preserve case option, which allows lowercase in alphabets or masks lowercase in sequences. The Roman option I think is unnecessary given arbitrary. The only thing we may want to do in the future is raw.

**Comment by ondovb** [comment]
Released in [v1.1](https://github.com/marbl/Mash/releases/tag/v1.1)
