### ISSUE TITLE
Please clarify help text

### ISSUE THREAD

**Issue by snayfach** [marbl/Mash#56]
The mash dist help text reads:

```
mash dist [options] <reference> <query> [<query>]

Options:
...Input...
  -l         List input. Each query file contains a list of sequence files, one
             per line. The reference file is not affected.
```

So I tried running it as follows:
`mash dist -p 10 -d 0.90 -t mash_out -l genome_paths.txt sketch.msh`

which produced the error:
```
Sketching genome_paths.txt (provide sketch file made with "mash sketch" to skip)...
ERROR: Did not find fasta records in "genome_paths.txt".
```

It took me a while, but I finally realized that the `-l genome_paths.txt` needed to be specified as a positional argument, and not an option. Finally, this worked:
`mash dist sketch.msh -l genome_paths.txt `

It think the help text could be clarified to help other users.

Thanks,
Stephen

**Comment by ondovb** [comment]
This option is confusing because `-l` is actually a flag (no argument), so it doesn't matter where you put it, as long as the reference and queries are in the right order. Would the following make it more clear?

`List input. Query files will be interpreted as lists of sequence files, one per line. The reference file is not affected.`

**Comment by snayfach** [comment]
Ah, OK I see now. I think the revised help text is more clear, but either are probably adequate. To me, this is even more clear:

```
List input. Lines in <query> specify file paths to sequence files, one per line. The reference file is not affected.
```
