### ISSUE TITLE
Is there a way to sketch 1,000 files in one line

### ISSUE THREAD

**Issue by ZeweiSong** [marbl/Mash#71]
Hi, 

I was wondering if there is an option that I can sketch many files in one command,  I would also like to get all pairwise distances.

Thanks!

Zewei

**Comment by ondovb** [comment]
Hi Zewei,

Not built into Mash, but you can use some shell trickery (see #26):
`echo a b c | xargs -n 1 mash sketch`.

For the distances, you would then need to `paste` them and give the result to `dist` twice (as ref and query). There has been some third-party effort to streamline this process since we haven't gotten to it (see https://github.com/lskatz/mashtree, #9, #66).

**Comment by ZeweiSong** [comment]
Thanks, I got it like this:

# Create sketch for all sequences (into a single file)
mash sketch *.fa -o genomes

# Compare individual sequence file with the sketch, and saved into a single dist file
echo *.fa | xargs -n 1 mash dist genomes.msh > dist.txt

I then just parser the txt file in python to keep the non-redundant pairs.

**Comment by alienzj** [comment]
For second step:
`mash dist genomes.msh genomes.msh`
