### ISSUE TITLE
Distance between complete genome and Plasmid

### ISSUE THREAD

**Issue by francescodc87** [marbl/Mash#76]
Hi all,
first of all I'd like to thank you for developing this software. I find it extremely useful.
I am using MASH to analyse a relatively large dataset and I found the following problem:

If I compute the distance between the a fasta file containing a complete genome (plasmids included) and another fasta file containing only one of those plasmid, I obtain a very low p-value a relatively small Jaccard index and a relative small distance. This makes complete sense as the plasmid is completely contained in the first fasta file. Looking at these outputs I am not able to discern between this case and cases where two genomes only happens to have those values, but not one is not completely contained into the other.

Do you know how I could tackle this problem? I believe that it would be enough if instead of only outputting the Jaccard Index (intersect(A,B)/union(A,B)), MASH could also output (intersect(A,B)/A and intersect(A,B)/B).
is there a simple way to obtain this.
Many thanks,
Francesco

**Comment by tiagofilipe12** [comment]
Hi @francescodc87 ,

I had a similar problem when I was developing [Plasmid Atlas](http://www.patlas.site). I discussed this issue that you raise here with @aphillippy and they assembled a nice command for `mash`, called `mash screen`. You can see their explanation on the new feature that came with version 2.0 in [this](https://genomeinformatics.github.io/mash-screen/) blog post.

But the idea is that you are trying to find a needle in a haystack. Mash screen in fact searches for what you asked (intersect(A,B)/A, being A the reference plasmid you are looking for and B your reads). The only catch here is that I am not sure if it can take `fasta` file instead of `fastq`. But maybe you can use your original fastq files that you used to generate that fastas that contain both the chromosome and plasmids.

I have tested mash screen for the same purpose you are trying to use here in pATLAS and for some samples that I have tested results are very similar to mapping or assembly approaches, however there are some samples that I still didn't figure it out but it appears to be related with plasmid sequences badly constructed (e.g. genes cut in half). However, I am still unsure.

Hope this helps.

**Comment by francescodc87** [comment]
Hi @tiagofilipe12,
it does help. Thank you very much!
