### ISSUE TITLE
GPL violation

### ISSUE THREAD

**Issue by kloetzl** [marbl/Mash#81]
The [Gnu Scientific Library](https://www.gnu.org/software/gsl/) is released under the normal GPLv3. As it does not come with the linking exception that means that every derived work linking to it must also be under GPLv3.

Not being a lawyer I see two options here: Change your license to GPL, or remove the option for linking against the GSL.

**Comment by ondovb** [comment]
We thought a lot about this too but concluded that GPL would not apply since we are distributing neither the GSL source code nor any object code that links to it, statically or dynamically (the binaries we release used Boost).

**Comment by skoren** [comment]
Right, to provide more detail, Mash can link against either Boost or GPL and all binaries we distribute are based on Boost. If a user chooses to install GPL themselves and link against it then yes, their compiled binary would be GPLed as well since it is a derivative work. However, the GPL code is ifdefed out in the case of Boost usage so no files/code from GPL are included in Mash in this case. Only the API is referenced.

I agree we should clarify the LICENSE and documentation so users understand if they link to GPL the resulting binary is GPL.

**Comment by kloetzl** [comment]
To be honest, I am unsure if having the option to compile a version of Mash that links against the GSL already counts as derivative work.

I just wanted to bring the license issue to your attention in case you missed it. But it seems you have already though about it. Feel free to close this issue as `wontfix`. ☺
