### ISSUE TITLE
Option to set the "ID" of a mash sketch

### ISSUE THREAD

**Issue by tseemann** [marbl/Mash#87]
I want my IDs to be neat, but `mash` is making it hard?

Case 1:
```
mash sketch -r -o foo DIR/R1.fq.gz
mash info foo.msh

  [Hashes]  [Length]  [ID]            [Comment]
  1000      105082    DIR/R1.fq.gz  - 
```

Case 2  (see closed https://github.com/marbl/Mash/issues/32)
```
cat R1.fq.gz R2.fq.gz  | mash sketch -r -o foo -
mash info foo.msh

 [Hashes]  [Length]  [ID]  [Comment]
  1000      1253918   -      -
```
I would just like a `-n` or `-I` option to set the `[ID]`.

And the `[Comment]` ?

**Comment by ondovb** [comment]
Implemented as `-I` and `-C` (comment).

**Comment by tseemann** [comment]
@ondovb I can't see any commits in master that refer to this?

Any chance of a 2.1 release for this feature?

Currently doing crazy named pipe setups to get proper IDs because when I do `<(zcat R1 R2)` i get the same name on everything `/dev/fd/63`.

**Comment by tseemann** [comment]
UPDATE: i see it's in the `triangle` mod.  Triangle does not work with the tools I have. It will need to be a full matrix, sorry.

**Comment by ondovb** [comment]
It's in https://github.com/marbl/Mash/commit/03b28ed82edaaadb649517d5aa6820a7dc54e882, which addresses both the ID issue and the read pair merging (I labelled round robin since it takes turns pulling reads from the input files to preserve `-c`, which I don't think anyone uses anyway :P ). 

It's only part of the `sketch` command so it shouldn't matter whether you use `dist` or `triangle` 
following that. Setting IDs directly in those would be possible but a little trickier parameter-wise.

Hopefully I'll get a release out soon but I want to make sure it's stable since there are some sketching changes. If you manage to break something in tip that would be helpful :).

**Comment by ondovb** [comment]
Ok, published [v2.1](https://github.com/marbl/Mash/releases/tag/v2.1).

**Comment by tseemann** [comment]
Thanks @ondovb  - I am going to run it now on 25,000 isolates. Will let you know what happens.

**Comment by ondovb** [comment]
This seems fixed? Reopen if not.
