### ISSUE TITLE
Hashing Forward and Reverse Strand

### ISSUE THREAD

**Issue by kloetzl** [marbl/Mash#91]
https://github.com/marbl/Mash/blob/aabd5925e7cfc097a8d89e2d8691ac4af5b95d37/src/mash/Sketch.cpp#L544-L580

As far as I understand the above code, the forward kmer (eg. `AAAA…`) and the reverse (`TTTT…`) are compared lexicographically. The smaller of the two gets hashed and (maybe) added to the sketch. However, as the kmers are hashed the lexicographically larger kmer (`TTTT…`) can well have a lower valued hash. Thus, I think both kmers have to be hashed and added to the sketch.

**Comment by sebhtml** [comment]
Hi kloetzl,

> The smaller of the two gets hashed and (maybe) added to the sketch. 

All hashes (32 bits or 64 bits) get pushed into the priority queue (in reverse order, from big to small).
The queue is used to keep only the minimum hashes of the sketch.
The priority queue has a maximum size. Beyond that size, a call to pop() is performed.

> Thus, I think both kmers have to be hashed and added to the sketch.

That would lead to non-uniform distribution of minimum hashes across the genome.
It would affect the Mash p-value probabilities, and pretty much everything going on.

Proof:

Consider a genome of length 50.
The location of a word is written as A-B, where A is the first nucleotide and B is the last nucleotide.
The genome of length 50 contains 20 words: one starting at 1-31, at 2-32, ..., and at 20-50.
At positions 1, 2, 3, 4, ..., 20, we have words w1, w2, ...,  w20 occurs respectively.
Suppose that every word is different.

Say the sketch has 10 hashes.

With 20 words, we have 20 canonical words, thus 20 hashes in total.

Suppose that 
hash(canonical(w1)) < hash(canonical(w2)) < hash(canonical(w3) < ... < hash(canonical(w20))

The 10 hashes in the sketch are those of words at position 1 to 10.
Thus, we cover 50% of positions. 

Now, if we also consider the not_canonical words, we have twice the number of hashes.
Each word generate 2 hashes. 20 * 2 = 40.

Suppose that:
hash(canonical(w1)) < hash(not_canonical(w1)) < hash(canonical(w2)) < hash(not_canonical(w2)) < hash(canonical(w3)) < hash(not_canonical(w3)) < ... hash(canonical(w20)) < hash(not_canonical(w20)).

The 10 min hashes are the ones of words at positions 1 to 5.
With what you propose, you would cover only 25% of position.

In a nutshell, the Mash software is a really good idea.
It is not going to replace Blast, because Blast is an aligner rand Mash is not.

The implementation of Mash is in C++ and reuse C++ STL containers. It also uses Cap'n Proto for the .msh files. In my opinion, Mash is a prime example of really good software engineering. Mash is tier 1. The best tier.

And your understanding of the Mash algorithms is incomplete.

Finally, an advise on optimization:

In your blog article https://blog.kloetzl.info/mash-the-pitiful-state-of-software-engineering-in-bioinformatics/
you describe optimizations using perf as a proof that what you did makes Mash faster.
But, you don't provide information that proves that your optimized Mash still does the same thing.

A critical part when optimizing software performance is to not change what the software does.

In the case of Mash, I would compute sha1sum of sketch files and "mash dist" output files, using the official Mash distribution, and using your modified Mash version.

Then, you compare these sha1sum. If they are not the same, your optimization is moot.

**Comment by kloetzl** [comment]
You have a good point that adding both the forward and reverse complement of one position to the sketch will skew the distribution. However, as it is implemented, the decision which strand to hash (forward or reverse complement) is based on the lexicographic ordering of the two kmers (as written in the paper). But won't this skew the distribution of hashed k-mers towards those having a higher A-C-content? And does that even matter, because other sketches will have the same skew?

**Comment by sebhtml** [comment]
Hey kloetzl,

DNA can be a single stranded or a double stranded molecule. In the life kingdoms Bacteria, Archaea, and Eukaryota, as far as I know, it is always double stranded. I think that single stranded DNA is only found in viruses.

For any word of DNA, there is a need for a standard form.

canonical
adjective
4. Mathematics. (of an equation, coordinate, etc.) in simplest or standard form.
http://www.dictionary.com/browse/canonical

The Mash algorithm always uses the low kmer, so it does not matter. You can think of it like that:
Each genomic position that can yield a kmer gets a shot at doing so by sending a canonical kmer to the competition that decides who gets incorporated in the sketch.

These 2 changes could be done independently though:

- Use the high word instead of the low word for the canonical word,

- Use max-hashes instead of min-hashes.

Note that the only case where it is tricky is when k is even and kmer = reverse_complement(kmer).
Example: k = 8, kmer = "TATATATA".
Unfortunately, "TATATATA" is not lower than its reverse complement "TATATATA", so is it canonical ?
Technically, it is not. So that word does not have a canonical word to represent it at the sketch kmer selection competition.

Allowing only odd lengths avoids this dilemma.

**Comment by kloetzl** [comment]
> The Mash algorithm always uses the low kmer, so it does not matter. You can think of it like that:
Each genomic position that can yield a kmer gets a shot at doing so by sending a canonical kmer to the competition that decides who gets incorporated in the sketch.

Thank you very much, now I get it. I mistook the “canonical” to mean ACGT-only; too many definitions of canonical.

The second reason I opened this pull request was that one can replace the code quoted above with a call to `strncmp` [e.g. see this change](https://github.com/kloetzl/Mash/commit/d0f0f9ab577013142bf56c2a7026e003132ab51b). That will simplify the code and give a measurable performance boost.

**Comment by sebhtml** [comment]
> Thank you very much, now I get it. I mistook the “canonical” to mean ACGT-only; too many definitions of canonical.

In the Star Wars universe, there is canon stuff (see http://starwars.wikia.com/wiki/Canon ) and non-canon stuff. That's the same thing with kmers.

> The second reason I opened this pull request was that one can replace the code quoted above with a call to strncmp e.g. see this change. That will simplify the code and give a measurable performance boost.

memcmp() could be faster than strncmp I think. Usually, memcmp is implemented with SSE.

**Comment by ondovb** [comment]
So is the result that `strncmp` or `memcmp` can be dropped in while preserving how canonical kmers are handled? And is one faster than the other? This would be an easy change, as long as it produces the same results.

**Comment by kloetzl** [comment]
`memcmp` should be fastest while maintaining full compatibility.

**Comment by kloetzl** [comment]
Fixed in 05aa0798384a19001842d6ccf7ef90563262f832. Thanks everyone!
